"""
ReportLab-based PDF export service for DD Consulting project reports.
Generates professional, widescreen (16:9) project reports with DD Consulting branding.
"""
import io
import logging
from datetime import datetime
from typing import Optional, List, Dict, Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import landscape, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Table,
    TableStyle,
    Spacer,
    PageBreak,
    KeepTogether
)
from reportlab.pdfgen import canvas

logger = logging.getLogger(__name__)

# DD Consulting Color Palette
DD_NAVY = colors.HexColor("#1B2A47")
DD_STEEL_BLUE = colors.HexColor("#4A9CC7")
DD_GOLD = colors.HexColor("#C9A84C")
DD_LIGHT_BG = colors.HexColor("#F8FAFC")
DD_DARK_TEXT = colors.HexColor("#0B1220")
DD_WHITE = colors.white
DD_GRAY = colors.HexColor("#6B7280")
DD_LIGHT_GRAY = colors.HexColor("#E5E7EB")

# 16:9 Widescreen dimensions (13.333" x 7.5")
WIDESCREEN_WIDTH = 13.333 * inch
WIDESCREEN_HEIGHT = 7.5 * inch


class NumberedCanvas(canvas.Canvas):
    """Custom canvas for headers and footers on every page."""
    
    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self._saved_page_states = []
    
    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()
    
    def save(self):
        """Add page info to each page (page x of y)"""
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_elements(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)
    
    def draw_page_elements(self, page_count):
        """Draw header and footer on each page."""
        self.saveState()
        
        # Footer
        self.setFont('Helvetica', 8)
        self.setFillColor(DD_GRAY)
        footer_text = "Generated by DD Planner • Confidential"
        footer_y = 0.3 * inch
        self.drawCentredString(WIDESCREEN_WIDTH / 2.0, footer_y, footer_text)
        
        # Page number (right side)
        page_num = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(WIDESCREEN_WIDTH - 0.5 * inch, footer_y, page_num)
        
        self.restoreState()


def create_styles() -> Dict[str, ParagraphStyle]:
    """Create custom paragraph styles for the document."""
    styles = getSampleStyleSheet()
    
    custom_styles = {
        'DDTitle': ParagraphStyle(
            'DDTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=24,
            textColor=DD_WHITE,
            alignment=TA_CENTER,
            spaceAfter=6
        ),
        'DDSubtitle': ParagraphStyle(
            'DDSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=14,
            textColor=DD_WHITE,
            alignment=TA_CENTER,
            spaceAfter=12
        ),
        'DDHeading': ParagraphStyle(
            'DDHeading',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=14,
            textColor=DD_NAVY,
            spaceAfter=8,
            spaceBefore=12
        ),
        'DDBody': ParagraphStyle(
            'DDBody',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            textColor=DD_DARK_TEXT,
            alignment=TA_JUSTIFY,
            leading=14
        ),
        'DDMetric': ParagraphStyle(
            'DDMetric',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=11,
            textColor=DD_NAVY,
            alignment=TA_CENTER
        ),
        'DDMetricValue': ParagraphStyle(
            'DDMetricValue',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            textColor=DD_GRAY,
            alignment=TA_CENTER
        ),
        'DDTableHeader': ParagraphStyle(
            'DDTableHeader',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=10,
            textColor=DD_WHITE,
            alignment=TA_LEFT
        ),
        'DDTableCell': ParagraphStyle(
            'DDTableCell',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            textColor=DD_DARK_TEXT,
            alignment=TA_LEFT
        ),
    }
    
    return custom_styles


def safe_str(value: Any, default: str = "N/A") -> str:
    """Safely convert any value to string, with fallback."""
    if value is None:
        return default
    if isinstance(value, (list, dict)):
        return str(value) if value else default
    return str(value)


def safe_date_format(date_value: Any, default: str = "N/A") -> str:
    """Safely format date values."""
    if not date_value:
        return default
    try:
        if isinstance(date_value, str):
            # Try parsing ISO format
            date_obj = datetime.fromisoformat(date_value.replace('Z', '+00:00'))
            return date_obj.strftime("%b %d, %Y")
        elif hasattr(date_value, 'strftime'):
            return date_value.strftime("%b %d, %Y")
        return str(date_value)
    except Exception:
        return str(date_value) if date_value else default


def build_header_banner(project: dict, styles: Dict[str, ParagraphStyle]) -> List:
    """Build the header banner with DD Consulting branding."""
    elements = []
    
    # Banner table with DD CONSULTING title
    project_name = safe_str(project.get('name', 'Untitled Project'))
    client_name = safe_str(project.get('client_name', 'N/A'))
    status = safe_str(project.get('status', 'Active'))
    report_date = datetime.now().strftime("%B %d, %Y")
    
    banner_data = [
        [
            Paragraph("DD CONSULTING", styles['DDTitle']),
        ],
        [
            Paragraph("Project Report", styles['DDSubtitle']),
        ],
    ]
    
    banner_table = Table(banner_data, colWidths=[12 * inch])
    banner_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), DD_NAVY),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
    ]))
    
    elements.append(banner_table)
    elements.append(Spacer(1, 0.15 * inch))
    
    # Project info row
    info_data = [[
        Paragraph(f"<b>Project:</b><br/>{project_name}", styles['DDBody']),
        Paragraph(f"<b>Client:</b><br/>{client_name}", styles['DDBody']),
        Paragraph(f"<b>Status:</b><br/>{status}", styles['DDBody']),
        Paragraph(f"<b>Report Date:</b><br/>{report_date}", styles['DDBody']),
    ]]
    
    info_table = Table(info_data, colWidths=[3 * inch, 3 * inch, 3 * inch, 3 * inch])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), DD_LIGHT_BG),
        ('GRID', (0, 0), (-1, -1), 0.5, DD_LIGHT_GRAY),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    
    elements.append(info_table)
    elements.append(Spacer(1, 0.2 * inch))
    
    return elements


def build_metrics_row(project: dict, styles: Dict[str, ParagraphStyle]) -> List:
    """Build metrics row showing key project KPIs."""
    elements = []
    
    # Extract metrics
    status = safe_str(project.get('status', 'Active'))
    health = safe_str(project.get('health', 'Green'), 'Green')
    start_date = safe_date_format(project.get('start_date'))
    end_date = safe_date_format(project.get('end_date'))
    budgeted_hours = safe_str(project.get('budgeted_hours', 'N/A'))
    
    # Calculate team load if allocations are available
    team_load = "N/A"
    if 'team_load' in project:
        team_load = f"{project['team_load']}%"
    
    metrics_data = [
        [
            Paragraph("Status", styles['DDMetric']),
            Paragraph("Health", styles['DDMetric']),
            Paragraph("Start Date", styles['DDMetric']),
            Paragraph("End Date", styles['DDMetric']),
            Paragraph("Budgeted Hours", styles['DDMetric']),
            Paragraph("Team Load", styles['DDMetric']),
        ],
        [
            Paragraph(status, styles['DDMetricValue']),
            Paragraph(health, styles['DDMetricValue']),
            Paragraph(start_date, styles['DDMetricValue']),
            Paragraph(end_date, styles['DDMetricValue']),
            Paragraph(budgeted_hours, styles['DDMetricValue']),
            Paragraph(team_load, styles['DDMetricValue']),
        ],
    ]
    
    col_width = 2 * inch
    metrics_table = Table(metrics_data, colWidths=[col_width] * 6)
    metrics_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), DD_STEEL_BLUE),
        ('BACKGROUND', (0, 1), (-1, 1), DD_WHITE),
        ('GRID', (0, 0), (-1, -1), 1, DD_STEEL_BLUE),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TEXTCOLOR', (0, 0), (-1, 0), DD_WHITE),
    ]))
    
    elements.append(metrics_table)
    elements.append(Spacer(1, 0.2 * inch))
    
    return elements


def build_section_box(title: str, content: str, styles: Dict[str, ParagraphStyle]) -> Table:
    """Build a section box with title and content."""
    data = [
        [Paragraph(title, styles['DDHeading'])],
        [Paragraph(content if content else "No information provided.", styles['DDBody'])],
    ]
    
    section_table = Table(data, colWidths=[12 * inch])
    section_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), DD_LIGHT_BG),
        ('BACKGROUND', (0, 1), (-1, 1), DD_WHITE),
        ('BOX', (0, 0), (-1, -1), 1, DD_LIGHT_GRAY),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
    ]))
    
    return section_table


def build_allocations_table(allocations: List[dict], styles: Dict[str, ParagraphStyle]) -> List:
    """Build team allocations table."""
    elements = []
    
    if not allocations or len(allocations) == 0:
        elements.append(Paragraph("No team allocations available.", styles['DDBody']))
        return elements
    
    elements.append(Paragraph("Team Allocations", styles['DDHeading']))
    
    # Table header
    table_data = [
        [
            Paragraph("Resource", styles['DDTableHeader']),
            Paragraph("Role", styles['DDTableHeader']),
            Paragraph("Allocation %", styles['DDTableHeader']),
        ]
    ]
    
    # Table rows
    for alloc in allocations:
        resource_name = safe_str(alloc.get('resource_name', 'Unknown'))
        role = safe_str(alloc.get('role', 'N/A'))
        allocation_pct = safe_str(alloc.get('allocation_percent', '0'), '0')
        
        table_data.append([
            Paragraph(resource_name, styles['DDTableCell']),
            Paragraph(role, styles['DDTableCell']),
            Paragraph(f"{allocation_pct}%", styles['DDTableCell']),
        ])
    
    alloc_table = Table(table_data, colWidths=[4 * inch, 4 * inch, 4 * inch])
    alloc_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), DD_STEEL_BLUE),
        ('BACKGROUND', (0, 1), (-1, -1), DD_WHITE),
        ('GRID', (0, 0), (-1, -1), 0.5, DD_LIGHT_GRAY),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TEXTCOLOR', (0, 0), (-1, 0), DD_WHITE),
    ]))
    
    elements.append(alloc_table)
    elements.append(Spacer(1, 0.2 * inch))
    
    return elements


def build_risks_table(risks: List[dict], styles: Dict[str, ParagraphStyle]) -> List:
    """Build active risks table."""
    elements = []
    
    if not risks or len(risks) == 0:
        elements.append(Paragraph("No active risks identified.", styles['DDBody']))
        return elements
    
    elements.append(Paragraph("Active Risks", styles['DDHeading']))
    
    # Table header
    table_data = [
        [
            Paragraph("Risk", styles['DDTableHeader']),
            Paragraph("Impact", styles['DDTableHeader']),
            Paragraph("Probability", styles['DDTableHeader']),
            Paragraph("Status", styles['DDTableHeader']),
        ]
    ]
    
    # Table rows
    for risk in risks:
        risk_desc = safe_str(risk.get('description', 'N/A'))
        impact = safe_str(risk.get('impact', 'Medium'))
        probability = safe_str(risk.get('probability', 'Medium'))
        status = safe_str(risk.get('status', 'Active'))
        
        table_data.append([
            Paragraph(risk_desc, styles['DDTableCell']),
            Paragraph(impact, styles['DDTableCell']),
            Paragraph(probability, styles['DDTableCell']),
            Paragraph(status, styles['DDTableCell']),
        ])
    
    risk_table = Table(table_data, colWidths=[5 * inch, 2.5 * inch, 2.5 * inch, 2 * inch])
    risk_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), DD_GOLD),
        ('BACKGROUND', (0, 1), (-1, -1), DD_WHITE),
        ('GRID', (0, 0), (-1, -1), 0.5, DD_LIGHT_GRAY),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TEXTCOLOR', (0, 0), (-1, 0), DD_WHITE),
    ]))
    
    elements.append(risk_table)
    elements.append(Spacer(1, 0.2 * inch))
    
    return elements


def build_status_update_section(status_updates: List[dict], styles: Dict[str, ParagraphStyle]) -> List:
    """Build recent accomplishments and next steps from latest status update."""
    elements = []
    
    if not status_updates or len(status_updates) == 0:
        return elements
    
    # Get the most recent status update
    latest_update = status_updates[0]
    
    accomplishments = safe_str(latest_update.get('accomplishments', ''), 'No recent accomplishments reported.')
    next_steps = safe_str(latest_update.get('next_steps', ''), 'No next steps defined.')
    
    elements.append(Paragraph("Recent Accomplishments", styles['DDHeading']))
    elements.append(Paragraph(accomplishments, styles['DDBody']))
    elements.append(Spacer(1, 0.15 * inch))
    
    elements.append(Paragraph("Next Steps", styles['DDHeading']))
    elements.append(Paragraph(next_steps, styles['DDBody']))
    elements.append(Spacer(1, 0.2 * inch))
    
    return elements


def build_project_pdf_reportlab(
    project: dict,
    risks: Optional[List[dict]] = None,
    allocations: Optional[List[dict]] = None,
    status_updates: Optional[List[dict]] = None
) -> bytes:
    """
    Build a professional, widescreen (16:9) project PDF report using ReportLab.
    
    This function is 100% crash-proof and will always return valid PDF bytes.
    
    Args:
        project: Project dictionary with keys like name, client_name, status, dates, etc.
        risks: Optional list of risk dictionaries
        allocations: Optional list of allocation dictionaries
        status_updates: Optional list of status update dictionaries
    
    Returns:
        bytes: PDF document as bytes
    """
    try:
        logger.info(f"Building ReportLab PDF for project: {project.get('name', 'Unknown')}")
        
        # Create buffer
        buffer = io.BytesIO()
        
        # Create document with widescreen dimensions
        doc = SimpleDocTemplate(
            buffer,
            pagesize=(WIDESCREEN_WIDTH, WIDESCREEN_HEIGHT),
            rightMargin=0.5 * inch,
            leftMargin=0.5 * inch,
            topMargin=0.5 * inch,
            bottomMargin=0.6 * inch,
            title=f"Project Report - {project.get('name', 'Untitled')}",
            author="DD Consulting"
        )
        
        # Initialize styles
        styles = create_styles()
        
        # Build document elements
        elements = []
        
        # 1. Header Banner
        elements.extend(build_header_banner(project, styles))
        
        # 2. Metrics Row
        elements.extend(build_metrics_row(project, styles))
        
        # 3. Executive Summary
        executive_summary = safe_str(
            project.get('executive_summary', ''),
            'No executive summary provided.'
        )
        summary_box = build_section_box("Executive Summary", executive_summary, styles)
        elements.append(summary_box)
        elements.append(Spacer(1, 0.15 * inch))
        
        # 4. Project Objective
        project_objective = safe_str(
            project.get('project_objective', ''),
            'No project objective defined.'
        )
        objective_box = build_section_box("Project Objective", project_objective, styles)
        elements.append(objective_box)
        elements.append(Spacer(1, 0.2 * inch))
        
        # 5. Team Allocations
        if allocations:
            elements.extend(build_allocations_table(allocations, styles))
        
        # 6. Active Risks
        if risks:
            elements.extend(build_risks_table(risks, styles))
        
        # 7. Status Update (Accomplishments & Next Steps)
        if status_updates:
            elements.extend(build_status_update_section(status_updates, styles))
        
        # Build the PDF
        doc.build(elements, canvasmaker=NumberedCanvas)
        
        # Get bytes
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        logger.info(f"Successfully generated PDF: {len(pdf_bytes)} bytes")
        return pdf_bytes
        
    except Exception as e:
        logger.error(f"Error generating ReportLab PDF: {str(e)}", exc_info=True)
        
        # Fallback: Return a minimal valid PDF
        try:
            buffer = io.BytesIO()
            doc = SimpleDocTemplate(
                buffer,
                pagesize=(WIDESCREEN_WIDTH, WIDESCREEN_HEIGHT),
                title="Error Report"
            )
            
            styles = getSampleStyleSheet()
            error_message = f"An error occurred while generating the PDF report: {str(e)}"
            elements = [
                Paragraph("PDF Generation Error", styles['Title']),
                Spacer(1, 0.3 * inch),
                Paragraph(error_message, styles['Normal'])
            ]
            
            doc.build(elements)
            pdf_bytes = buffer.getvalue()
            buffer.close()
            
            logger.info("Returned fallback error PDF")
            return pdf_bytes
            
        except Exception as fallback_error:
            logger.critical(f"Fallback PDF generation also failed: {str(fallback_error)}")
            # Return minimal valid PDF bytes as last resort
            return b'%PDF-1.4\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n3 0 obj\n<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> >> >> /MediaBox [0 0 960 540] /Contents 4 0 R >>\nendobj\n4 0 obj\n<< /Length 44 >>\nstream\nBT\n/F1 12 Tf\n50 500 Td\n(PDF Generation Error) Tj\nET\nendstream\nendobj\nxref\n0 5\n0000000000 65535 f\n0000000009 00000 n\n0000000058 00000 n\n0000000115 00000 n\n0000000317 00000 n\ntrailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n410\n%%EOF'
